name: zest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@17-php-versions
        with:
          configuration: phpunit.xml
          args: --coverage-text
